#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001
ENV ASPNETCORE_ENVIRONMENT=development
ENV ASPNETCORE_URLS=http://+:5000

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["TodoList.Identity.Service/TodoList.Identity.Service.csproj", "TodoList.Identity.Service/"]
COPY ["TodoList.Data/TodoList.Data.csproj", "TodoList.Data/"]
COPY ["TodoList.Domain/TodoList.Domain.csproj", "TodoList.Domain/"]
COPY ["TodoList.ResourceLibrary/TodoList.ResourceLibrary.csproj", "TodoList.ResourceLibrary/"]
RUN dotnet restore "TodoList.Identity.Service/TodoList.Identity.Service.csproj"
COPY . .
WORKDIR "/src/TodoList.Identity.Service"
RUN dotnet build "TodoList.Identity.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TodoList.Identity.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TodoList.Identity.Service.dll"]